
spring:
    #数据库连接信息
    datasource:
        master:
            driverClassName: com.mysql.jdbc.Driver
            type: com.alibaba.druid.pool.DruidDataSource
            url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
            password: root
            username: root
            druid:
                initial-size: 5
                max-active: 10
                max-wait: 10000
                min-idle: 10
        slave1:
            driverClassName: com.mysql.jdbc.Driver
            type: com.alibaba.druid.pool.DruidDataSource
            url: jdbc:mysql://localhost:3306/spring2?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
            password: root
            username: root
            druid:
                initial-size: 5
                max-active: 10
                max-wait: 10000
                min-idle: 10


#mybatis配置
mybatis:
    config:
        logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
        #开启下划线与驼峰式命名规则的映射,如first_name => firstName
        mapUnderscoreToCamelCase: true
        #允许使用自定义的主键值(比如由程序生成的UUID 32位编码作为键值)，数据表的PK生成策略将被覆盖
        useGeneratedKeys: false
    #mapper.xml的位置
#    mapper-locations: classpath:mapper/*.xml

#mybatis配置
mybatis-slave1:
    config:
        logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
        #开启下划线与驼峰式命名规则的映射,如first_name => firstName
        mapUnderscoreToCamelCase: true
        #允许使用自定义的主键值(比如由程序生成的UUID 32位编码作为键值)，数据表的PK生成策略将被覆盖
        useGeneratedKeys: false