
spring:
    #数据库连接信息
    datasource:
        master:
            driverClassName: com.mysql.jdbc.Driver
            type: com.alibaba.druid.pool.DruidDataSource
            url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
            password: Root_123456
#            password: root
            username: root
            druid:
                initial-size: 5
                max-active: 10
                max-wait: 10000
                min-idle: 10
        slave1:
            driverClassName: com.mysql.jdbc.Driver
            type: com.alibaba.druid.pool.DruidDataSource
            url: jdbc:mysql://localhost:3306/spring2?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
            password: Root_123456
            username: root
            druid:
                initial-size: 5
                max-active: 10
                max-wait: 10000
                min-idle: 10

